title: "Naida Vishad"
author: "Naida Vishad"
email: naidavishad81@gmail.com
description: "A professional reflective portfolio documenting my journey in Computer Engineering, Database Systems, and technical resilience."
url: "https://naidavishad.github.io"
baseurl: ""
github_username: naidavishad07
permalink: /:title/
lang: "en"
show_excerpts: true
show_frame: true
show_sidebar: false

navigation:
  - {title: "Home", url: "/", icon: "home"}
  - {title: "About Me", url: "/about/", icon: "user"}
  - {title: "My Engineering Story", url: "/blog/", icon: "book-open"}
  - {title: "Semester 1", url: "/semester1/", icon: "graduation-cap"}
  - {title: "Semester 2", url: "/semester2/", icon: "graduation-cap"}

external:
  - {title: GitHub, icon: github, url: "https://github.com/naidavishad07"}
  - {title: Mail, icon: envelope, url: "mailto:naidavishad81@gmail.com"}


plugins:
  - jekyll-feed
  - jekyll-seo-tag
