title: "Nahida Wishad Ali Khan"
email: naidavishad81@gmail.com
description: "Registration No: 2025-BSCPE-140 | Semester 2 Journey"

# Theme settings
theme: minima
remote_theme: jekyll/minima

# Navigation
header_pages:
  - index.md
  - blog.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
